import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <nav className="bg-[#F3F3E0] fixed w-full z-20 top-0 start-0 border--[#CBDCEB]">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a
              href="/"
              className="flex items-center space-x-3 rtl:space-x-reverse"
            >
              <img
                src="https://flowbite.com/docs/images/logo.svg"
                className="h-8"
                alt="Logo"
              />
              <span className="self-center text-2xl font-semibold whitespace-nowrap text-[#133E87]">
                A-Ing!
              </span>
            </a>
            <div className="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
              <a href="/main">
                <button
                  type="button"
                  className="text-white bg-[#133E87] hover:bg-[#608BC1] focus:ring-4 focus:outline-none focus:ring-[#CBDCEB] font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                >
                  Get started
                </button>
              </a>
            </div>
            <div
              className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
              id="navbar-sticky"
            >
              <ul className="flex flex-col p-4 md:p-0 mt-4 font-medium border border-[#CBDCEB] rounded-lg bg-[#CBDCEB] md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-[#F3F3E0]">
                <li>
                  <a
                    href="/home"
                    className="block py-2 px-3 text-white bg-[#133E87] rounded-sm md:bg-transparent  md:p-0 md:text-[#133E87] md:hover:text-[#608BC1]"
                    aria-current="page"
                  >
                    Home
                  </a>
                </li>
                <li>
                  <a
                    href="/about"
                    className="block py-2 px-3 text-[#133E87] rounded-sm hover:bg-[#CBDCEB] md:hover:bg-transparent md:p-0 md:hover:text-[#608BC1]"
                  >
                    About
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="pt-30">{children}</div>
      </body>
    </html>
  );
}
